language: go
env:
- GIMME_OS=linux GIMME_ARCH=arm
install:
- go get -d -v golang.org/x/sys/unix
script:
- go build -o pi-init github.com/israelshirk/pi-init/src/projects.bytemark.co.uk/pi-init2
before_deploy:
- zip -r pi-init.zip cmdline.txt config.txt setup_vars.sh ssh pi-init appliance
deploy:
  branch: master
  provider: releases
  api_key:
    secure: "01ENvC7Ym21JiuSM0rhleIAHD77Vz8jehPuLUKGo2bdev5F3d5mC6XM/Dt+JMxXphk3doX9EhBpK68ca8LuAaiRGPIjSmPzv9hFZaxlU2x7SQ4Q1sz64Kv7gPdH3SAn4wAkxaRXs57X6GXw6/v3oB+EMAXqeGXYFEYp9vg5q8yIE+BSZVSitbatyvniimNucVGTiNXrZE2hsA91ZHEhmmhChEnybj1P6E8LeOCSVcs61BjU9Qamj+cLB6dYQf2ToIt8fZVBYnflvrujkhjizG40nHyF2ZSIm+gD5G10+JI9MdnZ3oODEg+zXV6Gs6A0gjvO4p6+YUaGpYrzHWAW0C+hkwb+8vkrfa2Zs5bwdrw6CJEjrqBht9bQx//BobziFVO/mDvX9Hru/DT7Aj636Hnvkj0D1mt3C+ubKvO+69JVeP1wnMK4c3PlT5AcW+Qb0ERAKlIkRmfQ8LRQPTwyyl4hrgBUoZIQgNzxe5rofWC/w6gPpZIcLMhiuJoWwFXvtUE9W8V1AQ5K0kmEMwHbdZ90WPUZ9CyLMHWu9nfYMeMw1UmlpUGVjEQ2lFQ6DMQIXXEXePbvYEJv4UIzPPCz3g1xZIgx8A+vqryw3k7j+GESzo0LwovKur3YeLArIyZvFsCuRuwlzPe+ILU6pG3Kan+aHyyxy+IWNUTB1uof59nY="
  skip_cleanup: true
  file: pi-init.zip
  on:
    repo: israelshirk/pi-init
    tags: true
