#!/bin/bash -v

. /boot/setup_vars.sh

# Remove this file if you want to re-run the setup
#
if [ -f /boot/pi-install.done ] ; then
	exit 0
fi

# Update the system and install a package or two that we need
#
export DEBIAN_FRONTEND=noninteractive
apt-get -q update
apt-get -q -y dist-upgrade
if [ -n "$PACKAGES" ]; then
	apt-get -q -y install $PACKAGES
fi

# Configure unattended-upgrades
# FIXME: configure to update rtlsdr-ogn as well
sed -i 's/^\/\/      "o=Raspbian,n=jessie"/        "o=Raspbian,n=jessie"/g' /etc/apt/apt.conf.d/50unattended-upgrades
sed -i 's/^\/\/Unattended-Upgrade::Automatic-Reboot "false";/Unattended-Upgrade::Automatic-Reboot "true";/g' /etc/apt/apt.conf.d/50unattended-upgrades

raspi-config --expand-rootfs
sed -i "s/^\s*LANG=\S*/LANG=$LOCALE/" /etc/default/locale
dpkg-reconfigure -f noninteractive locales

sed -i /etc/default/keyboard -e "s/^XKBLAYOUT.*/XKBLAYOUT=\"$KEYMAP\"/"
dpkg-reconfigure -f noninteractive keyboard-configuration
invoke-rc.d keyboard-setup start
setsid sh -c 'exec setupcon -k --force <> /dev/tty1 >&0 2>&1'
udevadm trigger --subsystem-match=input --action=change

rm -f /etc/localtime
echo "$TIMEZONE" > /etc/timezone
dpkg-reconfigure -f noninteractive tzdata

touch /boot/pi-install.done

systemctl enable arducopter

exit 0

# TODO: run normal resize script